### ISSUE TITLE
Export tabluler data in CSV format

### ISSUE THREAD

**Issue by devanghingu** [wharton/drf-excel#82]
Currently the package exporting data in `xlsx` format. can we export tabular data in CSV format?

**Comment by FlipperPA** [comment]
@devanghingu There are a few other packages which support this: https://www.django-rest-framework.org/api-guide/renderers/#csv

My friend Mjumbe Poe maintains this one: https://github.com/mjumbewu/django-rest-framework-csv

I hope one of those options works, but that's why we never build in support.
